language: go

go:
  - 1.8.x
  - tip

sudo: false
install:
  - go get -v -t ./...

go_import_path: github.com/aQuaYi/ToDaMoon 

script: go test ./...
notifications:
  email:
    recipients:
      - aQua@aQuaYi.com
    on_success: always